# Copyright Forest Supply. All Rights Reserved.
# Autor: Mauro Rambo, mauro.e.rambo@gmail.com
# Date: 27-08-2023
# SPDX-License-Identifier: Apache-2.0
#
OrdererOrgs:
    - Name: Orderer
      Domain: forestsupply.com
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: Org1
      Domain: org1.forestsupply.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org2
      Domain: org2.forestsupply.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org3
      Domain: org3.forestsupply.com
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
  